apiVersion: v1
kind: Service
metadata:
  name: ingredients-service
spec:
  selector:
    app: ingredients
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingredients
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingredients
  template:
    metadata:
      labels:
        app: ingredients
    spec:
      containers:
      - name: ingredients
        image: ingredients:latest
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: recipes-service
spec:
  selector:
    app: recipes
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recipes
  template:
    metadata:
      labels:
        app: recipes
    spec:
      containers:
      - name: recipes
        image: recipes:latest
        env:
          - name: PORT_RECIPES
            value: "80"
        envFrom:
        - configMapRef:
            name: global-config
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: calories-service
spec:
  selector:
    app: calories
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: calories
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calories
  template:
    metadata:
      labels:
        app: calories
    spec:
      containers:
      - name: calories
        image: calories:latest
        env:
          - name: PORT
            value: "80"
        envFrom:
        - configMapRef:
            name: global-config
        - secretRef:
            name: mongodb-credentials
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
