apiVersion: v1
kind: ConfigMap
metadata:
  name: global-config
data:
  RECIPE_API_URL: "http://recipes-service:80"
  CALORIE_API_URL: "http://calories-service:80"
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-credentials
type: Opaque
data:
  MONGO_ROOT_PASSWORD: bW90ZGVwYXNzZQ==
  MONGO_USERNAME: YWRtaW4=
